---
title: "ProjectTwo"
author: "Maks Nikiforov and Mark Austin"
date: "Due 10/31/2021"
params: 
      channel: ""
---


```{r image setup, include=FALSE}

##For markdown automation need a different image folder 
##  for each of the 6 channels
if (params$channel=="data_channel_is_bus") {
  knitr::opts_chunk$set(fig.path = "images/bus/")
} else if (params$channel=="data_channel_is_entertainment") {
  knitr::opts_chunk$set(fig.path = "images/entertainment/")
} else if (params$channel=="data_channel_is_lifestyle") {
  knitr::opts_chunk$set(fig.path = "images/lifestyle/")
} else if (params$channel=="data_channel_is_socmed") {
  knitr::opts_chunk$set(fig.path = "images/socmed/")
} else if (params$channel=="data_channel_is_tech") {
  knitr::opts_chunk$set(fig.path = "images/tech/")
} else if (params$channel=="data_channel_is_world") {
  knitr::opts_chunk$set(fig.path = "images/world/")
} 
#knitr::opts_chunk$set(fig.path = "images/")

```



```{r load packages,message=FALSE,echo=FALSE}
   library(tidyverse)
   library(caret)
   library(knitr)
```

## Introduction  


## Data  


```{r import data, message=FALSE}


fullData<-read_csv("./data/OnlineNewsPopularity.csv")


```

Using `r params$channel`

```{r subset for channel}

params$channel


channelData<-fullData %>% filter(eval(as.name(params$channel))==1) 

##test code to confirm by str the filter is as expected
str(channelData)

###Need to drop other channel variables??

```


## Summarizations  


```{r graphOneA}
##For now this is just a test graph to test out automation
g<-ggplot(data = channelData,
          aes(x=rate_positive_words,y=self_reference_avg_sharess))
g + geom_point()

```


## Modeling  

```{r splitting data}

#Using set.seed per suggestion so that work will be reproducible


```


```{r train linear regression model one}

```


```{r train linear regression model two}

```


```{r train random forest model}

```


```{r train boosted tree model}

```


## Model Comparisions  



```{r test linear regression model one}

```


```{r test linear regression model two}

```


```{r test random forest model}

```


```{r test boosted tree model}

```





